# Generated by Django 5.0.3 on 2024-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPQ_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='jam_mauli',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='jam_pulang',
            field=models.TimeField(),
        ),
    ]
