# Generated by Django 5.0.3 on 2024-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPQ_app', '0002_alter_jadwal_jam_mauli_alter_jadwal_jam_pulang'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='title',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
